# Generated by Django 2.1.5 on 2019-01-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20190118_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='directions',
            field=models.TextField(default=' '),
        ),
    ]
