# Generated by Django 2.1.5 on 2019-01-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_handout_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='display_definitions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='handout',
            name='display_words',
            field=models.BooleanField(default=True),
        ),
    ]
