# Generated by Django 2.1.5 on 2019-01-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_auto_20190122_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='column_order',
            field=models.TextField(default=' '),
        ),
    ]
