# Generated by Django 2.1.5 on 2019-01-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_handout_column_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='image_url',
            field=models.TextField(default=''),
        ),
    ]
